# === Augment YOLO DS Config (YAML) ===
# Pass to augment_yolo_ds.py via: --aug_yaml /path/to/augment_config.yaml

# --- top-level controls matching your pipeline settings ---
out_ext: ".jpg"
multiplier: 2
include_images_without_labels: true
seed: 1337
write_yaml: true

# --- Albumentations transform (defaults mirror the script's previous CLI defaults) ---
transform:
  hflip_p: 0.5
  vflip_p: 0.5
  affine:
    p: 0.7
    scale: [0.9, 1.1]
    translate_percent: [-0.05, 0.05]
    rotate: [-15, 15]
    shear: [-5, 5]
  random_resized_crop:
    p: 0.5
    scale: [0.9, 1.0]
    ratio: [0.9, 1.1]
  color_jitter:
    p: 0.5
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1

# --- tiling (grid sweep) — copied from your pipeline values ---
tiling:
  enable: true
  tile_size: 512
  tile_overlap: 0.40
  min_tile_vis: 0.05
  keep_empty_tiles: false
  from_aug: false

# --- zoom crops (object-centric) — copied from your pipeline values ---
zoom_crops:
  enable: true
  scales: [0.35, 0.5, 0.7]
  per_obj: 2
  on: "both"            # disc | cup | both | any
  out_size: 640
  jitter: 0.05
  min_vis: 0.10
  from_aug: false
  keep_empty: false

# --- multi-scale sliding zoom sweep — copied from your pipeline values ---
zoom_sweep:
  enable: true
  scales: [0.35, 0.5, 0.7]
  overlap: 0.25
  min_vis: 0.10
  keep_empty: false
  out_size: 640
  from_aug: false