# === OOP Preprocessing Pipeline Config ===

# ---- Core project paths ----
project_dir: "/Users/carlosperez/PycharmProjects/MedSAM"

# (Single-dataset keys kept for back-compat; ignored during 'collect' when 'datasets:' is present)
images_root: "/Users/carlosperez/OneDrive_UBC/Ipek_Carlos/GlaucomaDatasets/SMDG-19/full-fundus/full-fundus"
disc_masks:  "/Users/carlosperez/OneDrive_UBC/Ipek_Carlos/GlaucomaDatasets/SMDG-19/optic-disc/optic-disc"
cup_masks:   "/Users/carlosperez/OneDrive_UBC/Ipek_Carlos/GlaucomaDatasets/SMDG-19/optic-cup/optic-cup"

# ---- Outputs ----
labels_dir:      "/Users/carlosperez/PycharmProjects/MedSAM/data/labels"
yolo_split:      "/Users/carlosperez/PycharmProjects/MedSAM/data/yolo_split"
yolo_aug:        "/Users/carlosperez/PycharmProjects/MedSAM/data/yolo_split_aug"
yolo_roi:        "/Users/carlosperez/PycharmProjects/MedSAM/data/yolo_split_cupROI"
yolo_disc_only:  "/Users/carlosperez/PycharmProjects/MedSAM/data/yolo_split_disc_only"
viz_out:         "/Users/carlosperez/PycharmProjects/MedSAM/data/viz_labels"

# ---- Which stages to run ----
all: true         # pipeline_oop defaults to collect,split,save,augment,disc_only,roi when steps is not set
steps: null       # or e.g. ["collect","split","save","augment","disc_only","roi"]

# ---- Small subset mode (applies after collect, before split) ----
subset_n: 50
subset_seed: 4343
subset_copy: false       # only relevant if your save step copies files; OOP uses symlink by default
prefer_copy: false       # set true on filesystems that dislike symlinks (OneDrive, some NAS, etc.)

# ---- Split config ----
val_frac: 0.15
test_frac: 0.15
seed: 1337
patient_regex: ""        # optional regex with one capturing group if you need custom subject_id grouping

# ---- Augment (OOP Augmentor) ----
augment_enabled: true
aug_yaml: "./configs/augment.yaml"
augment_splits: ["train"]     # augment only the train split by default
augment_multiplier: 2         # N augmented versions per original
augment_out_ext: ".jpg"       # output image format for augmented images
include_images_without_labels: false

# ---- Disc-only (OD single-class derived) ----
disc_only_from_aug_train: true    # if true and yolo_aug exists, OD train comes from augmented set
disc_only_train_splits: ["train"]  # (kept for future; current OOP builder takes whole train)
disc_only_copy_images: false       # false = symlink
disc_only_drop_empty: false        # drop items whose labels become empty after filtering to disc-only

# ---- ROI (cup-only dataset built from OD ROI) ----
roi_pad_pct: 0.0
keep_roi_negatives: false
roi_from_aug: false

# ---- Multi-dataset blocks (used by 'collect' in OOP pipeline) ----
datasets:
  - tag: smdg19
    images_root: "/Users/carlosperez/OneDrive_UBC/Ipek_Carlos/GlaucomaDatasets/SMDG-19/full-fundus/full-fundus"
    disc_masks:  "/Users/carlosperez/OneDrive_UBC/Ipek_Carlos/GlaucomaDatasets/SMDG-19/optic-disc/optic-disc"
    cup_masks:   "/Users/carlosperez/OneDrive_UBC/Ipek_Carlos/GlaucomaDatasets/SMDG-19/optic-cup/optic-cup"
    recursive: false
    exclude_name_contains: ["PAPILA"]

  - tag: rimone
    images_root: "/Users/carlosperez/OneDrive_UBC/Ipek_Carlos/GlaucomaDatasets/Rim-One/Organized_Rim-One/fundus"
    disc_masks:  "/Users/carlosperez/OneDrive_UBC/Ipek_Carlos/GlaucomaDatasets/Rim-One/Organized_Rim-One/optic-disc"
    cup_masks:   "/Users/carlosperez/OneDrive_UBC/Ipek_Carlos/GlaucomaDatasets/Rim-One/Organized_Rim-One/optic-cup"
    recursive: true