# === OOP Preprocessing Pipeline Config (HPC) ===

# ---- Core project paths ----
project_dir: "/scratch/st-ipor-1/cperez/MedSAM"

# (Single-dataset keys kept for back-compat; ignored during 'collect' when 'datasets:' is present)
images_root: "/scratch/st-ipor-1/cperez/MedSAM/bounding_box/data/images"
disc_masks:  "/scratch/st-ipor-1/cperez/MedSAM/bounding_box/data/disc_masks"
cup_masks:   "/scratch/st-ipor-1/cperez/MedSAM/bounding_box/data/cup_masks"

# ---- Outputs ----
labels_dir:      "/scratch/st-ipor-1/cperez/MedSAM/data/labels"
yolo_split:      "/scratch/st-ipor-1/cperez/MedSAM/data/yolo_split"
yolo_aug:        "/scratch/st-ipor-1/cperez/MedSAM/data/yolo_split_aug"
yolo_roi:        "/scratch/st-ipor-1/cperez/MedSAM/data/yolo_split_cupROI"
yolo_disc_only:  "/scratch/st-ipor-1/cperez/MedSAM/data/yolo_split_disc_only"
viz_out:         "/scratch/st-ipor-1/cperez/MedSAM/data/viz_labels"

# ---- Which stages to run ----
all: true         # defaults to collect,split,save,augment,disc_only,roi when steps is not set
steps: null       # or e.g. ["collect","split","save","augment","disc_only","roi"]

# ---- Small subset mode (applies after collect, before split) ----
subset_n: 0                 # 0 disables subsetting on HPC; set >0 to enable
subset_seed: 4343
subset_copy: false          # OOP uses symlinks by default
prefer_copy: false          # set true only if your FS disallows symlinks

# ---- Split config ----
val_frac: 0.15
test_frac: 0.15
seed: 1337
patient_regex: ""           # optional regex with ONE capturing group for patient ID

# ---- Augment (OOP Augmentor) ----
augment_enabled: true
aug_yaml: "/scratch/st-ipor-1/cperez/MedSAM/configs/augment.yaml"
augment_splits: ["train"]   # augment only the train split
augment_multiplier: 2       # N augmented versions per original
augment_out_ext: ".jpg"     # output format for augmented images
include_images_without_labels: false

# ---- Disc-only (OD single-class derived) ----
disc_only_from_aug_train: false    # match local behavior; set true if you want OD train from augmented
disc_only_train_splits: ["train"]
disc_only_copy_images: false       # false = symlink
disc_only_drop_empty: false

# ---- ROI (cup-only dataset built from OD ROI) ----
roi_pad_pct: 0.0
keep_roi_negatives: false
roi_from_aug: false

# ---- Multi-dataset blocks (used by 'collect' in OOP pipeline) ----
datasets:
  - tag: smdg19
    images_root: "/arc/project/st-ipor-1/carlosp/fundus_data/SMDG-19/full-fundus/full-fundus"
    disc_masks:  "/arc/project/st-ipor-1/carlosp/fundus_data/SMDG-19/optic-disc/optic-disc"
    cup_masks:   "/arc/project/st-ipor-1/carlosp/fundus_data/SMDG-19/optic-cup/optic-cup"
    recursive: false
    exclude_name_contains: ["PAPILA"]

  - tag: rimone
    images_root: "/arc/project/st-ipor-1/carlosp/fundus_data/Organized_Rim-One/fundus"
    disc_masks:  "/arc/project/st-ipor-1/carlosp/fundus_data/Organized_Rim-One/optic-disc"
    cup_masks:   "/arc/project/st-ipor-1/carlosp/fundus_data/Organized_Rim-One/optic-cup"
    recursive: true   # often nested; safest to enable